language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_script:
    - composer install

after_success:
    - bash <(curl -s https://codecov.io/bash)

script: phpunit --coverage-text
